module.exports = [
  { township: "Thongwa", township_mm: "သုံးခွ" },
  { township: "Kyauktan", township_mm: "ကျောက်တန်း" },
  { township: "Insein", township_mm: "အင်းစိန်" },
  { township: "Hmawbi", township_mm: "မှော်ဘီ" },
  { township: "Kayan", township_mm: "ခရမ်း" },
  {
    township: "Dagon Myothit (North)",
    township_mm: "ဒဂုံမြို့သစ်မြောက်ပိုင်း",
  },
  { township: "Pazundaung", township_mm: "ပုဇွန်တောင်" },
  { township: "Kungyangon", township_mm: "ကွမ်းခြံကုန်း" },
  { township: "Kyauktada", township_mm: "ကျောက်တံတား" },
  { township: "Lanmadaw", township_mm: "လမ်းမတော်" },
  { township: "Hlegu", township_mm: "လှည်းကူး" },
  { township: "Htantabin", township_mm: "ထန်းတပင်" },
  { township: "Botahtaung", township_mm: "ဗိုလ်တထောင်" },
  { township: "Mayangone", township_mm: "မရမ်းကုန်း" },
  { township: "Kyeemyindaing", township_mm: "ကြည့်မြင်တိုင်" },
  { township: "Latha", township_mm: "လသာ" },
  { township: "Mingalartaungnyunt", township_mm: "မင်္ဂလာတောင်ညွန်" },
  { township: "Tamwe", township_mm: "တာမွေ" },
  { township: "Thaketa", township_mm: "သာကေတ" },
  {
    township: "Dagon Myothit (East)",
    township_mm: "ဒဂုံမြို့သစ်အရှေ့ပိုင်း",
  },
  { township: "Ahlone", township_mm: "အလုံ" },
  { township: "Shwepyithar", township_mm: "ရွှေပြည်သာ" },
  { township: "Sanchaung", township_mm: "စမ်းချောင်း" },
  { township: "Kawhmu", township_mm: "ကော့မှုး" },
  { township: "North Okkalapa", township_mm: "မြောက်ဥက္ကလာပ" },
  { township: "Cocokyun", township_mm: "ကိုကိုးကျွန်း" },
  { township: "Yankin", township_mm: "ရန်ကင်း" },
  { township: "Thanlyin", township_mm: "သန်လျှင်" },
  { township: "Mingaladon", township_mm: "မင်္ဂလာဒုံ" },
  {
    township: "Dagon Myothit (South)",
    township_mm: "ဒဂုံမြို့သစ်တောင်ပိုင်း",
  },
  { township: "Kamaryut", township_mm: "ကမာရွတ်" },
  { township: "Thingangyun", township_mm: "သင်္ဃန်းကျွန်း" },
  { township: "Bahan", township_mm: "ဗဟန်း" },
  { township: "Dawbon", township_mm: "ဒေါပုံ" },
  { township: "Pabedan", township_mm: "ပန်းပဲတန်း" },
  { township: "Twantay", township_mm: "တွံတေး" },
  { township: "Seikgyikanaungto", township_mm: "ဆိပ်ကြီးခနောင်တို" },
  { township: "Dagon", township_mm: "ဒဂုံ" },
  { township: "Seikkan", township_mm: "ဆိပ်ကမ်း" },
  { township: "South Okkalapa", township_mm: "တောင်ဥက္ကလာပ" },
  { township: "Taikkyi", township_mm: "တိုက်ကြီး" },
  { township: "Hlaing", township_mm: "လှိုင်" },
  { township: "Dala", township_mm: "ဒလ" },
  { township: "Hlaingtharya", township_mm: "လှိုင်သာယာ" },
  {
    township: "Dagon Myothit (Seikkan)",
    township_mm: "ဒဂုံမြို့သစ်ဆိပ်ကမ်း",
  },
];
