export const townshipData = [
  "Dagon Myothit(ဒဂုံမြို့သစ်)",
  "Pazundaung(ပုဇွန်တောင်)",
  "Kyauktada(ကျောက်တံတား)",
  "Lanmadaw(လမ်းမတော်)",
  "Botahtaung(ဗိုလ်တထောင်)",
  "Mayangone(မရမ်းကုန်း)",
  "Kyeemyindaing(ကြည့်မြင်တိုင်)",
  "Latha(လသာ)",
  "Mingalartaungnyunt(မင်္ဂလာတောင်ညွန်)",
  "Tamwe(တာမွေ)",
  "Thaketa(သာကေတ)",
  "Ahlone(အလုံ)",
  "Shwepyithar(ရွှေပြည်သာ)",
  "Sanchaung(စမ်းချောင်း)",
  "North Okkalapa(မြောက်ဥက္ကလာပ)",
  "Yankin(ရန်ကင်း)",
  "Thanlyin(သန်လျှင်)",
  "Mingaladon(မင်္ဂလာဒုံ)",
  "Kamaryut(ကမာရွတ်)",
  "Thingangyun(သင်္ဃန်းကျွန်း)",
  "Bahan(ဗဟန်း)",
  "Dawbon(ဒေါပုံ)",
  "Pabedan(ပန်းပဲတန်း)",
  "Dagon(ဒဂုံ)",
  "South Okkalapa(တောင်ဥက္ကလာပ)",
  "Taikkyi(တိုက်ကြီး)",
  "Hlaing(လှိုင်)",
  "Hlaingtharya(လှိုင်သာယာ)",

  "Pyin Oo Lwin(ပြင်ဦးလွင်)",
  "Kyaukse (ကျောက်ဆည်)",
  "Chanmyathazi(ချမ်းမြသာစည်)",
  "Chanayethazan(ချမ်းအေးသာဇံ)",
  "Thazi(သာစည်)",
  "Pyigyitagon(ပြည်ကြီးတံခွန်)",
  "Meiktila(မိတ္ထီလာ)",
  "Aungmyaythazan(အောင်မြေသာဇံ)",
  "Tada-U(တံတားဦး)",
  "Mahaaungmyay(မဟာအောင်မြေ)",
  "Pyawbwe(ပျော်ဘွယ်)",
  "Amarapura(အမရပူရ)",
];

export const YangonData = [
  "Dagon Myothit(ဒဂုံမြို့သစ်)",
  "Pazundaung(ပုဇွန်တောင်)",
  "Kyauktada(ကျောက်တံတား)",
  "Lanmadaw(လမ်းမတော်)",
  "Botahtaung(ဗိုလ်တထောင်)",
  "Mayangone(မရမ်းကုန်း)",
  "Kyeemyindaing(ကြည့်မြင်တိုင်)",
  "Latha(လသာ)",
  "Mingalartaungnyunt(မင်္ဂလာတောင်ညွန်)",
  "Tamwe(တာမွေ)",
  "Thaketa(သာကေတ)",
  "Ahlone(အလုံ)",
  "Shwepyithar(ရွှေပြည်သာ)",
  "Sanchaung(စမ်းချောင်း)",
  "North Okkalapa(မြောက်ဥက္ကလာပ)",
  "Yankin(ရန်ကင်း)",
  "Thanlyin(သန်လျှင်)",
  "Mingaladon(မင်္ဂလာဒုံ)",
  "Kamaryut(ကမာရွတ်)",
  "Thingangyun(သင်္ဃန်းကျွန်း)",
  "Bahan(ဗဟန်း)",
  "Dawbon(ဒေါပုံ)",
  "Pabedan(ပန်းပဲတန်း)",
  "Dagon(ဒဂုံ)",
  "South Okkalapa(တောင်ဥက္ကလာပ)",
  "Taikkyi(တိုက်ကြီး)",
  "Hlaing(လှိုင်)",
  "Hlaingtharya(လှိုင်သာယာ)",
];

export const MandalayData = [
  "Pyin Oo Lwin(ပြင်ဦးလွင်)",
  "Kyaukse (ကျောက်ဆည်)",
  "Chanmyathazi(ချမ်းမြသာစည်)",
  "Chanayethazan(ချမ်းအေးသာဇံ)",
  "Thazi(သာစည်)",
  "Pyigyitagon(ပြည်ကြီးတံခွန်)",
  "Meiktila(မိတ္ထီလာ)",
  "Aungmyaythazan(အောင်မြေသာဇံ)",
  "Tada-U(တံတားဦး)",
  "Mahaaungmyay(မဟာအောင်မြေ)",
  "Pyawbwe(ပျော်ဘွယ်)",
  "Amarapura(အမရပူရ)",
];
